### ISSUE TITLE
Cannot compile on macOS 

### ISSUE THREAD

**Issue by haifengkao** [teufelaudio/UIExtensions#65]
[UIWindow+MotionEnded](https://github.com/teufelaudio/UIExtensions/blob/master/Sources/UIExtensions/Extensions/UIWindow%2BMotionEnded.swift) needs to wrap "import UIKit" by `#if canImport(UIKit)`

**Comment by melle** [comment]
Looks like an oversight by us. Do you mind sending a PR to fix that?
